services:
  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-service
    ports:
      - "8020:8020"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      SMART_KIOSK_RAG_CONFIG_OVERRIDE_PATHS: /app/rag-service/config.container.yaml
      MALLOC_MMAP_THRESHOLD_: "13107200"
    volumes:
      - ./config.container.yaml:/app/rag-service/config.container.yaml:ro
      - ./models:/app/rag-service/models
      - ./storage:/app/rag-service/storage
      - ./.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
